### ISSUE TITLE
Investigate current xpub behaviour of creating new user if no profile

### ISSUE THREAD

**Issue by erezmus** [libero/continuum-auth#28]
Currently in xpub, if a user logs in but has not profile, then a new user is created:

https://github.com/elifesciences/elife-xpub/blob/cd0bd9fef9c838c543897e041694741d27d20086/packages/component-model-user/entities/user/index.js#L37

A new uuid is created (via objection... i think) and used as the userId.

We would need to replicate that behaviour to maintain parity

**Comment by diversemix** [comment]
Writing a document here.... https://docs.google.com/document/d/1oEMhSxCicNjNZFa5TAB7kIsvFQT_zWLGLhlYJtOSCwQ/edit?usp=sharing

**Comment by erezmus** [comment]
conversation started, closing
